[package]
name = "dependency-checker-test"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.130"
tokio = "1.0.0"
actix-web = "3.3.2"
reqwest = "0.11.0"
sqlx = "0.5.0"

[dev-dependencies]
mockall = "0.10.0"
tokio-test = "0.4.0" 